// <auto-generated />
namespace my_app_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserIsActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIsActive));
        
        string IMigrationMetadata.Id
        {
            get { return "202301081839420_User IsActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
